### ISSUE TITLE
Not handling being in a subdirectory

### ISSUE THREAD

**Issue by fufroma** [mduplouy/acme-web-manager#5]
Installed in a sub directory.

Configured a rewritebase in my htaccess.

On the main page, when I click on "Create a new domain to manage", add_domain send a 302 redirect to `/`

**Comment by mduplouy** [comment]
Should be fixed by 77de9012cae1da08fb9dc6b86cb4181bc1b01c55, template was missing a var

**Comment by fufroma** [comment]
Fixed
